(() => {
  const chapters=[...document.querySelectorAll('.chapter')];
  const count=document.querySelector('#progressCount');
  const bar=document.querySelector('#progressBar');
  const name=document.querySelector('#progressName');
  const observer=new IntersectionObserver(entries=>{const v=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!v)return;const i=chapters.indexOf(v.target);count.textContent=`${String(i+1).padStart(2,'0')} / ${String(chapters.length).padStart(2,'0')}`;bar.style.width=`${((i+1)/chapters.length)*100}%`;name.textContent=v.target.dataset.name;},{threshold:[.3,.55]});
  chapters.forEach(c=>observer.observe(c));

  document.querySelectorAll('[data-aid]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-aid]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const aid=Number(btn.dataset.aid),rest=100-aid;document.querySelector('#aidPart').style.width=`${aid}%`;document.querySelector('#restPart').style.width=`${rest}%`;document.querySelector('#aidPart b').textContent=`${aid} %`;document.querySelector('#restPart b').textContent=`${rest} %`;document.querySelector('#shareText').textContent=`Bei ${aid} Prozent Beihilfe verbleiben ${rest} Prozent Restkosten.`;}));

  const pathCopy={gkv:'<h3>Die freiwillige GKV kann richtig sein.</h3><p>Zum Beispiel bei bestimmten Familienkonstellationen, pauschaler Beihilfe oder gesundheitlichen Gründen.</p>',pkv:'<h3>Beihilfe plus PKV kann richtig sein.</h3><p>Der Dienstherr übernimmt den beihilfefähigen Anteil. Versichert wird der verbleibende Rest. Entscheidend sind Tarifleistung, Gesundheitsprüfung und Familienplanung.</p>'};
  document.querySelectorAll('[data-path]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-path]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelector('#pathCopy').innerHTML=pathCopy[btn.dataset.path];}));

  const state={children:0};
  const out=document.querySelector('#childrenOutput'),field=document.querySelector('#childrenField'),system=document.querySelector('#system'),result=document.querySelector('#restResult'),aidV=document.querySelector('#aidVisual'),restV=document.querySelector('#restVisual'),text=document.querySelector('#restText');
  function update(){const status=document.querySelector('input[name="status"]:checked')?.value||'active';let aid=50;if(status==='retired'||status==='spouse')aid=70;if(status==='child')aid=80;if(status==='active'&&state.children>=2)aid=70;field.hidden=status!=='active';if(system.value==='pauschal'){result.textContent='Sondermodell';aidV.style.width='50%';restV.style.width='50%';aidV.textContent='Beitragszuschuss';restV.textContent='eigener Beitrag';text.textContent='Bei pauschaler Beihilfe beteiligt sich der Dienstherr am Krankenversicherungsbeitrag. Die Landesregelung muss geprüft werden.';return;}const rest=100-aid;result.textContent=`${rest} %`;aidV.style.width=`${aid}%`;restV.style.width=`${rest}%`;aidV.textContent=`Beihilfe ${aid} %`;restV.textContent=`Rest ${rest} %`;text.textContent=system.value==='land'?`Typischer Ausgangswert: ${rest} Prozent Restkosten. Landesrecht kann abweichen.`:`Ein Beihilfetarif würde typischerweise ${rest} Prozent Restkosten abbilden.`;}
  document.querySelectorAll('input[name="status"]').forEach(i=>i.addEventListener('change',update));document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>{state.children=Math.max(0,Math.min(6,state.children+Number(b.dataset.step)));out.textContent=state.children;update();}));system.addEventListener('change',update);

  const stories={today:'<small>Heute prüfen</small><h3>Nicht nur den Preis. Den Einstieg in den späteren Tarif.</h3><p>Anwärterbeitrag, Umstellung, Selbstbeteiligung und Leistungsausschlüsse gehören gemeinsam betrachtet.</p>',later:'<small>Später relevant</small><h3>Leistungsgrenzen werden sichtbar, wenn Sie sie brauchen.</h3><p>Psychotherapie, Zahnersatz, Hilfsmittel und stationäre Wahlleistungen müssen konkret in den Bedingungen stehen.</p>',future:'<small>Langfristig prüfen</small><h3>Beihilfesatz, Alterungsrückstellungen und Tarifentwicklung.</h3><p>Der heutige Beitrag ist nur ein Teil der Rechnung.</p>'};
  document.querySelectorAll('[data-story]').forEach(b=>b.addEventListener('click',()=>document.querySelector('#storyDetail').innerHTML=stories[b.dataset.story]));

  document.querySelector('#contactForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);const subject=encodeURIComponent(`Beihilfe-Anfrage: ${d.get('topic')}`);const body=encodeURIComponent(`Vorname: ${d.get('firstname')}\nKontakt: ${d.get('contact')}\nThema: ${d.get('topic')}\n\nNachricht:\n${d.get('message')||''}`);location.href=`mailto:kontakt@hanse-konzept.de?subject=${subject}&body=${body}`;});
  update();
})();
